### ISSUE TITLE
CWGroup fails to form nested test groups

### ISSUE THREAD

**Issue by DonaldKellett** [monadius/coq_codewars#1]
Suppose I have the following test suite:

```coq
Require Solution.
Require Import Preloaded Check FunctionalExtensionality.
From CW Require Import Loader.

CWGroup "Solution.bubblesort_correct".
  CWGroup "should have the correct type".
    Goal True.
      check_type Solution.bubblesort_correct (is_a_sorting_algorithm bubblesort).
    Abort.
  CWEndGroup.
  CWGroup "should not assume any axioms other than (dependent) functional extensionality".
    CWTest Solution.bubblesort_correct Assumes functional_extensionality_dep.
  CWEndGroup.
CWEndGroup.
```

I'd assume that it would give the following structured output:

****

Solution.bubblesort_correct
- should have the correct type
  - Solution.bubblesort_correct : Type is correct
- should not assume any axioms other than (dependent) functional extensionality
  - Axiom Test

****

But instead, the top-level test group ("Solution.bubblesort_correct") doesn't show at all and the two sub-groups end up at the top level instead:

![螢幕截圖 2019-07-19 13 19 26](https://user-images.githubusercontent.com/7777884/61511176-7c293580-aa28-11e9-865c-e0d773ece48b.png)

**Comment by monadius** [comment]
Do I understand correctly that it is enough to output `<IT::>` for nested groups? I am working on it now. I do not plan to introduce new commands: `CWGroup` will automatically output `<IT::>` for nested groups. I also want to add time in milliseconds after `<COMPLETEDIN::>`.

**Comment by kazk** [comment]
`<DESCRIBE::>` is for a group and `<IT::>` is for a test case.

If `<PASSED::>`/`<FAILED::>` is inside `<IT::>`, nested `<DESCRIBE::>` should work.

**Comment by kazk** [comment]
`describe -> assertion` is already hack so I'd prefer each assertion result (or a set of assertion results) to be inside `<IT::>`.

**Comment by monadius** [comment]
Is it better to have separate commands for `<DESCRIBE::>` and `<IT::>`? Something like `CWDescribe` (replacing `CWGroup`) and `CWIt`? Is it OK to output `<IT::>` without previous `<DESCRIBE::>`?

**Comment by kazk** [comment]
Yeah, it's ok to have a top level `<IT::>`. Some test frameworks doesn't have `<DESCRIBE::>`. But we can't have nested `<IT::>`

- `describe -> it -> assertion_result` Good
- `describe -> describe -> it -> assertion_result` Good
- `describe -> assertion_result` OK (I think this is mainly for Codewars test frameworks that doesn't really care about the test structure)
- `it -> assertion_result` OK
- `assertion_result` OK
- `describe -> describe -> assertion_result` don't work
- `it -> it -> assertion_result` not allowed

For naming, I think `CWGroup` is better. I'm not sure what to name `<IT::>` though (`CWTest`, `CWCase`, something like that and fits in Coq better). Words like "describe" and "it" are from BDD style test framework.

**Comment by monadius** [comment]
I [made](https://github.com/Codewars/coq_codewars/commit/e095bc62b5a7e1d70c57f7284e3d90f341d7498a) the following changes:

- Added a new command `CWTestCase`. This command outputs `<IT::>`.

- Added a new command `CWEnd` for finishing test cases. This command is optional because `CWEndGroup` automatically finishes test cases (and also finishes a group) and `CWTestCase` finishes previous test cases also.

- Added a new command `CWAssert`. This is an alias of `CWTest`. I want to rename the existing command `CWTest` to `CWAssert`. But I cannot do it right now without breaking existing kata. So it is a temporary solution: after this update is deployed I would like to replace `CWTest` in all existing kata (5 kata which use the plugin) to `CWAssert`. Then I also want to rename `CWTestCase` to `CWTest`.

- I also [implemented](https://github.com/Codewars/coq_codewars/commit/e095bc62b5a7e1d70c57f7284e3d90f341d7498a) another form of the `CWAssert` command for type checking.

Example: [cw_example/test.v](https://github.com/Codewars/coq_codewars/blob/master/cw_example/test.v).

@kazk: Please test the updated plugin (specifically, check the output formatting of `cw_example/test.v`).

The question to everyone: what do you think about command names?

**Comment by kazk** [comment]
`cw_example/test.v` should look like
![image](https://user-images.githubusercontent.com/639336/61572849-07222400-aa59-11e9-9a76-0e96ba1fadd5.png)

---

Can you change the file names of the example to `Preloaded.v`, `Solution.v`, `SolutionTest.v`? I had to edit `test.v` to make it run because of the module name difference.

**Comment by monadius** [comment]
The formatting looks good. The example files are renamed.

**Comment by DonaldKellett** [comment]
> 5 kata which use the plugin

Probably 15 or so since I updated all my previously authored Coq Kata (13 in total) to use `CW.Loader`. Renaming `CWTest` to `CWAssert` and such should be an easy fix though so I don't mind if the breaking changes are introduced straight away; just give me a heads-up when they are deployed so I can fix my Kata right away :+1:

**Comment by monadius** [comment]
I decided to follow @DonaldKellett's suggestion and renamed some commands. I made the following changes: `CWTest` -> `CWAssert`, `CWTestCase` -> `CWTest`, `CWEnd` -> `CWEndTest`. When the updated plugin is deployed some kata will be broken but it will not take a long time to fix them. I don't think it will cause any problems.

@DonaldKellett: here is an example of test code for your Mergesort kata:

```coq
Require Solution.
Require Import Preloaded FunctionalExtensionality.
From CW Require Import Loader.

CWGroup "Solution.mergesort_correct".
  CWTest "should have the correct type".
    CWAssert Solution.mergesort_correct : (is_a_sorting_algorithm mergesort).
  CWTest "should not assume any axioms other than (dependent) functional extensionality".
    CWAssert Solution.mergesort_correct Assumes functional_extensionality_dep.
CWEndGroup.
```

**Comment by kazk** [comment]
I'll try deploying this later tonight if I have the time or tomorrow. I'll close this issue when I do.

**Comment by kazk** [comment]
Deployed
